# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[aws]
symbol = "îŒ½ "
disabled = true
# style = "bold blue"
# symbol = "ğŸ…° "
# displayed_items = "region"
# [aws.region_aliases]
# ap-southeast-2 = "au"
# us-east-1 = "va"
# 
# [battery]
# full_symbol = "ï•¸"
# charging_symbol = "ï–ƒ"
# discharging_symbol = "ï–‚"
# 
# [conda]
# symbol = "ï„Œ "
# 
# [docker]
# symbol = "ïŒˆ "
# 
# [elixir]
# symbol = "î‰µ "
# 
# [elm]
# symbol = "î˜¬ "

[directory]
truncate_to_repo = true
truncation_length = 8

[git_branch]
symbol = "ï˜ "

[git_commit]
prefix = "("
suffix = ")"
commit_hash_length = 4

[git_status]
disabled = false

[golang]
symbol = "î˜§ "
# 
# [haskell]
# symbol = "î˜Ÿ "
# 
# [hg_branch]
# symbol = "ï˜ "
# 
# [java]
# symbol = "î‰– "
# 
# [julia]
# symbol = "î˜¤ "
# 
# [memory_usage]
# symbol = "ï¡š "
# 
# [nim]
# symbol = "ïš¤ "
# 
# [nix_shell]
# symbol = "ï‹œ "
# 
# [nodejs]
# symbol = "î‰ "
# 
# [package]
# symbol = "ï£– "
# 
# [php]
# symbol = "î˜ˆ "
# 
# [python]
# symbol = "î˜† "
# 
# [ruby]
# symbol = "îˆ¾ "
# 
# [rust]
# symbol = "ï€“ "
 

[kubernetes]
symbol = "â›µ "
style = "dimmed green"
disabled = false
# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"

[terraform]
show_version = false
